kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: harbor.home.hoffmeister.biz/diztortion/podman:alpine
    environment:
      HARBOR_USERNAME:
        from_secret: docker_username
      HARBOR_PASSWORD:
        from_secret: docker_password
    commands:
      - whoami
      - podman system reset --force
      - echo $HARBOR_PASSWORD | podman login --username $HARBOR_USERNAME --password-stdin harbor.home.hoffmeister.biz
      - podman info
      - make
