kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: harbor.home.hoffmeister.biz/diztortion/podman:alpine
    environment:
      BUILDAH_ISOLATION: chroot
      STORAGE_DRIVER: vfs
      DOCKER_HOST: tcp://localhost:2375
    commands:
      - whoami
      - podman unshare
      - podman info
      - make
  - name: tag image
    image: harbor.home.hoffmeister.biz/docker.io-cache/library/alpine
    commands:
      - apk update
      - apk info tftp-hpa | grep "installed size:" | sed -E 's/.+-(\d+\.\d+(\.\d+)?-r\d+) installed size:/\1/' > .tags
  - name: docker
    image: harbor.home.hoffmeister.biz/docker.io-cache/plugins/kaniko
    settings:
      repo: harbor.home.hoffmeister.biz/diztortion/tftp-hpa
      registry: harbor.home.hoffmeister.biz
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
